import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, ArrowLeft } from 'lucide-react';

const Terms = () => {
  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      <header className="bg-white border-b border-slate-200 py-4 px-6">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <ShieldCheck className="text-primary h-6 w-6" />
            <span className="text-xl font-bold text-primary">FightYourPCN</span>
          </Link>
          <Link to="/" className="text-slate-600 hover:text-primary font-medium flex items-center gap-2 transition">
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
        </div>
      </header>

      <main className="flex-grow py-12 px-6">
        <div className="max-w-3xl mx-auto bg-white p-8 md:p-12 rounded-2xl shadow-sm border border-slate-200">
          <h1 className="text-3xl font-bold text-primary mb-8">Terms & Conditions</h1>
          
          <div className="prose prose-slate max-w-none space-y-6 text-slate-700">
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using FightYourPCN, you agree to be bound by these Terms and Conditions. If you do not agree, you may not use our services.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">2. Description of Service</h2>
              <p>FightYourPCN provides an AI-powered tool to help UK drivers draft appeal letters for parking tickets (PCNs). We provide information and document templates only. We are not a law firm and do not provide legal advice.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">3. No Legal Advice</h2>
              <p className="font-semibold text-primary">The information provided on this website and in generated documents does not constitute legal advice. No solicitor-client relationship is formed between you and FightYourPCN.</p>
              <p>You are responsible for reviewing and verifying the accuracy and appropriateness of any document generated through our service before submitting it to any authority.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">4. Fees and Payments</h2>
              <p>We charge a one-time fee of £1 per appeal draft generated. All payments are processed securely via Stripe. Fees are non-refundable once the draft has been generated.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">5. Limitation of Liability</h2>
              <p>FightYourPCN shall not be liable for any unsuccessful appeals, fines, or penalties incurred. We do not guarantee the success of any appeal draft generated by our AI.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">6. User Responsibilities</h2>
              <p>You agree to provide accurate information when using our service. You are responsible for meeting all deadlines set by the relevant authorities for appealing your parking ticket.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">7. Governing Law</h2>
              <p>These terms are governed by the laws of England and Wales.</p>
            </section>
          </div>
        </div>
      </main>

      <footer className="py-8 px-6 text-center text-xs text-slate-500">
        <p>&copy; {new Date().getFullYear()} FightYourPCN. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default Terms;
